//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS0001
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamStats
    {
        public int Id { get; set; }
        public string TeamId { get; set; }
        public int Singles { get; set; }
        public int Doubles { get; set; }
        public int Triple { get; set; }
        public int HomeRuns { get; set; }
        public int BaseOnBalls { get; set; }
        public int HitByPitch { get; set; }
        public int Sacrifice { get; set; }
        public int DoublePlayed { get; set; }
        public int StrikeOut { get; set; }
        public int FGOuts { get; set; }
        public int Plates { get; set; }
    }
}
